service: roomies-expenses-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: ${self:custom.ExpensesQueue.arn}

functions:
  count:
    handler: src/handlers/count.handler
    events:
      - http:
          method: GET
          path: /count

  expenseReasons:
    handler: src/handlers/expenseReasons.handler
    events:
      - http:
          method: GET
          path: /expenseReasons

  users:
    handler: src/handlers/users.handler
    events:
      - http:
          method: GET
          path: /users

  totals:
    handler: src/handlers/totals.handler
    events:
      - http:
          method: GET
          path: /totals

  expensesMonthly:
    handler: src/handlers/expensesMonthly.handler
    events:
      - http:
          method: GET
          path: /expensesMonthly

  expensesPaged:
    handler: src/handlers/expensesPaged.handler
    events:
      - http:
          method: GET
          path: /expensesPaged

  createExpense:
    handler: src/handlers/createExpense.handler
    events:
      - http:
          method: POST
          path: /createExpense

  createNotificationSub:
    handler: src/handlers/createNotificationSub.handler
    events:
      - http:
          method: POST
          path: /createNotificationSub

  deleteExpense:
    handler: src/handlers/deleteExpense.handler
    events:
      - http:
          method: DELETE
          path: /deleteExpense/{id}

custom:
  ExpensesQueue:
    arn: ${cf:roomies-notification-service-${self:provider.stage}.ExpensesQueueArn}
    url: ${cf:roomies-notification-service-${self:provider.stage}.ExpensesQueueUrl}
